1111philo/apolis-app

index.html
fixes 404 error on root creation / app render
=> update main.jsx to main.tsx

CONTRIBUTING.md
=> Update CONTRIBUTING.md with instructions to run local staging env and staging and prod urls

src/main.tsx, src/types.d.ts, src/views/NewVisitView.tsx, tsconfig.json
- **main.jsx :: remove: dead code; fix: small syntax issue**
- **fix: some compiler errors; add: more comp settings to tsconfig; add: ReactSelectOption type**
- **NewVisitView.tsx :: remove: dead code and comment**
=> Minor changes and fixes -- nothing meaningful

src/routes/new-notification.tsx
- new notification view ready for api integration
=> add new-notification view

src/routes/guests_.$guestId.tsx, src/routes/users_.$userId.tsx, src/types.d.ts
- **fix: guest notification count**
- **add: guest profile view; add: true api fetch user; change: user profile to match guest profile (italics); add: props to User type**
=> Add user profile view (users/id)

src/App.tsx, src/routes/__root.tsx, src/routes/services_.$serviceId.tsx, src/types.d.ts
- services subnav is populated with live services
- live service name is displayed
=> ServiceView init api integration

src/routes/users.tsx, src/types.d.ts
There's a BUG in Users and Guests views where the search bar loses focus between characters typed.
=> Add users view. BUG: search.

src/App.tsx, src/routes/new-notification.tsx, src/routes/services_.$serviceId.tsx
- remove visits from navigation
- warn user if no guest selected in notification creation
- show success modal if notification created successfully
- ready for api integration when api is successful
=> new notification view api ready

src/App.tsx, src/routes/services_.$serviceId.tsx
- guests can be moved to complete and queued
- fixes bug with app nav and react duplicate element key
=> service view - move guests

src/App.tsx, src/routes/services_.$serviceId.tsx
- services page correctly renders when navigated to
- subnav styling remains consistent
=> fix: services subnav

src/lib/api/index.ts, src/lib/api/service.ts, src/routes/services_.$serviceId.tsx
- guests can be moved around to different statuses, view reactive to reflect user input
- async functions refactored, now live in `api/service`
- index added for imports from `/api`
=> services view guest status reactive

src/App.tsx, src/routes/users.tsx
- New Visit is now the first link in the Nav bar
- fixes new user button onClick
=> fix new user button, move new visit nav item

package.json, pnpm-lock.yaml, src/App.tsx
- init tanstack react query for async state management
=> Tanstack query init

src/routes/new-notification.tsx
- uses react query to fetch all guests
- ensures user attaches guest with notification
- includes notification creation confirmation
=> add live api for notification view

src/lib/api/service.ts, src/routes/add-service.tsx, src/routes/new-notification.tsx
- add-service handles submission of new service, prevents submission if required name is not present and when new service would be a duplicate
- adds fetchServices() util
- minor tweaks in new-notification view
=> add-service view with live api

src/lib/api/guest.ts, src/lib/components/FeedbackMessage2.tsx, src/routes/guests_.$guestId.tsx, src/types.d.ts
- **change: ui upgrade -- use cards instead of lists; add: separate list for archive notifs; add: completed services**
- **impl: delete guest; add: feedback message**
- **impl: edit guest, but it's broken seemingly bc the api isn't working**
=> UI facelift and impl delete and edit guest from Guest Profile

src/routes/services_.$serviceId.tsx
- previous commit had omitted the service quota and broke the page, now the service quota is included
=> hotfix: services quota

src/lib/components/EditServiceForm.tsx, src/routes/add-service.tsx, src/routes/services_.$serviceId.tsx
- trigger app reload with navigate hook so that service name and subnav item are updated after they are edited
=> use navigate for service page reload

src/lib/api/index.ts, src/lib/components/GuestSelectSearch.tsx, src/lib/utils/guestOpts.ts, src/lib/utils/index.ts, src/routes/new-notification.tsx, src/routes/new-visit.tsx
- both views now use the same guest search select input
- factored out a standalone GuestSelectSearch component
- created guestOpts.ts, moved some guest option specific utils there
=> refactor: new-visit and new-notification now with GuestSelectSearch

src/lib/utils/useGlobalStore.ts, src/routes/__root.tsx, src/routes/_auth.tsx, src/routes/_auth.users.tsx, src/types.d.ts
- **add: isAdmin check to conditionally display New User button; NOTE: big diff bc formatting -- changes are lines including/surrounding**
- **move: authUser and authUserIsAdmin to route ctx, mixed in in the /_auth beforeLoad func**
=> Conditionally display New User button in Users view

src/App.tsx, src/routes/_auth.services_.$serviceId.tsx
- edit service only available to admins now
- style: conditionally render dropdown divider in services subnav
=> auth: edit service admin only

src/routes/__root.tsx
- sort services for preferred subnav order
=> fix services subnav

src/lib/api/service.ts, src/lib/components/QueuedTable.tsx, src/routes/__root.tsx, src/routes/_auth.services_.$serviceId.tsx, src/types.d.ts
- sort services in fetchServices(), use util in root
- add beforeLoad on services view which returns the service as part of the context
- reduce slot numbers down to only available for initial available slot state
=> services view api integration

src/lib/api/service.ts, src/lib/components/CompletedTable.tsx, src/lib/components/OccupiedSlotCard.tsx, src/lib/components/QueuedTable.tsx, src/routes/_auth.services_.$serviceId.tsx
- buttons on services view are now ready for API once [blockers](https://github.com/1111philo/apolis-app/issues/10#issuecomment-2640600448) are resolved
- guest names and IDs are clickable, will navigate to their profile
=> services buttons api ready

src/lib/api/service.ts, src/lib/components/CompletedTable.tsx, src/lib/components/OccupiedSlotCard.tsx, src/lib/components/QueuedTable.tsx, src/routes/_auth.new-notification.tsx, src/routes/_auth.services_.$serviceId.tsx
- service details views all responsive
- buttons working with staging api
- some adjustments to service fetch/util funcs
=> use tanstack query

src/lib/components/AvailableSlotCard.tsx, src/lib/components/OccupiedSlotCard.tsx
- secondary action button in slot cards is now under a dropdown
- slot card height adjusted to be responsive
=> fix: slot card secondary button

src/lib/utils/util.ts, src/routes/_auth.guests_.$guestId.tsx
- **fix: Guest Profile > notifications sorting**
- **refactor: factor out sortByTimeDescending()**
=> Fix: Guest Profile > notifications sorting

src/lib/api/auth.ts, src/lib/api/service.ts, src/lib/components/Services.tsx, src/routeTree.gen.ts, src/routes/_auth.services_.$serviceId.tsx, src/routes/index.tsx, src/routes/reset-password.tsx
Reverts 1111philo/apolis-app#124
=> Revert "Revert "Staging""

src/lib/components/GuestProfileForm.tsx
- **fix: Users view > new user form > no confirm password match check**
- **fix: #141 Guest Profile > form > form change indicator throwing false positive**
=> Fix #141 - Guest Profile > form > form change indicator throwing false positive for new guests

src/lib/api/service.ts, src/lib/components/QueuedTable.tsx, src/lib/components/QueuedTableRow.tsx, src/routes/_auth.services_.$serviceId.tsx
Resolves issue #162 
- "Slot #" dropdown only has slot options available based on the current occupied slots AND current slot intentions (selected per guest but not assigned yet)
=> fix: available slot options

src/routes/_auth.new-visit.tsx
@its-all-waves Searches for Courtyard, falls back to first service.
=> Try to set courtyard as default

src/lib/utils/util.ts, src/routes/_auth.new-visit.tsx
=> Fix how the clear function works so it also sets the default

src/lib/components/QueuedTableRow.tsx
=> Add an icon after the guests name if they have an active notification

src/lib/components/QueuedTable.tsx, src/routes/_auth.services_.$serviceId.tsx
- add guestsCompleted dependency in useEffect for fetchSlotOptions()
Resolves #202
=> update available slot options after guest marked completed

package-lock.json, yarn.lock
We need a package-lock.json here so that npm can install the exact same dependencies that are used everywhere else and then run the tests.
=> Run npm install, updates yarn.lock and creates package-lock

src/lib/components/TablePager.tsx, src/routes/_auth._admin.users.tsx, src/routes/_auth.guests.tsx
=> Fix table pager overflow

README.md, docs/project_goals.md
- move legacy requirements and UI/UX planning into `docs/project_goals.md`
=> update readme with improved layout and dev info

CONTRIBUTING.md, README.md
* init /docs, add readme template, move legacy readme to /docs/project_goals.md
* remove playground.ts file, was tracked and pushed by mistake
* Add workflow to run tests (#221)
* Update bug_report.md
Make this more friendly
* Create run_node_tests.js.yml
---------
* fix: table pager too long / overflowing
* fix: #215: invalid date on new notification; sync with API PR #29: return whole notification
* update README with improved layout and development info
* add contributing protocol details
- includes some small tweaks in README.md
---------
=> add contributing protocol details (#243)
